name: demo7_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_webview_plugin: ^0.4.0
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.4.0
  # HTTP
  # https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0


  # .env 多环境支持
  # https://pub.flutter-io.cn/packages/flutter_dotenv
  flutter_dotenv: ^5.0.0


  # 日志查看，体质调试查看
  # https://pub.flutter-io.cn/packages/logger
  logger: ^1.0.0


  # 组件通信 EventBus
  # https://pub.flutter-io.cn/packages/event_bus
  event_bus: ^2.0.0


  # 查找文件系统上的常用位置
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.2


  # 设备权限检查
  # https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^8.1.2


  # 状态管理
  # https://pub.flutter-io.cn/packages/provider
  provider: ^5.0.0


  # 读取 pubspec.yaml 文件内容
  # https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.2


  shared_preferences: ^2.0.6

  # 极光推送
  # https://pub.flutter-io.cn/packages/jpush_flutter
  jpush_flutter: ^2.1.4


  # 获取设备信息
  # https://pub.flutter-io.cn/packages/device_info
  device_info: ^2.0.2


  # Toast 提示
  # https://pub.flutter-io.cn/packages/bot_toast
  bot_toast: ^4.0.1


  # 加载动画组件
  # 配合 BotToast 使用，美化 Loading 组件样式。
  # https://pub.flutter-io.cn/packages/flutter_spinkit
  flutter_spinkit: ^5.0.0


  # 图片压缩
  # https://pub.flutter-io.cn/packages/flutter_image_compress
  flutter_image_compress: ^1.0.0


  # 震动反馈
  # https://pub.flutter-io.cn/packages/vibrate
  vibrate: ^0.0.4


  # 缓存图片
  # https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.0.0


  # 安卓安装 apk
  # https://pub.flutter-io.cn/packages/install_plugin
  install_plugin: ^2.0.1


  # 文件大小转换
  # https://pub.flutter-io.cn/packages/filesize
  filesize: ^2.0.1

  # Url Launcher
  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.0.9

  # 相册读写
  # https://pub.flutter-io.cn/packages/image_gallery_saver
  image_gallery_saver: ^1.6.9

  # loadingBtn
  # https://pub.flutter-io.cn/packages/future_button
  future_button: ^0.1.2
  timeline_tile: ^2.0.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.2
  photo_view: ^0.12.0
  images_picker: ^1.2.4
  # 微信支付
  # https://pub.flutter-io.cn/packages/fluwx
  fluwx: ^3.6.1+2
  # 支付宝支付
  # https://pub.flutter-io.cn/packages/tobias
  tobias: ^2.1.2+1
  # iconfont库
  # https://pub.dev/packages/iconfont
  iconfont: ^1.0.0

  # 路由库
  # https://pub:dev/packages/fluro
  fluro: ^2.0.3

  # html_editor富文本编辑器
  # https://pub.dev/packages/html_editor_enhanced
  html_editor_enhanced: ^2.3.0

  # dart string 转html编码
  # https://pub.dev/packages/html_character_entities/install
  html_character_entities: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 字体
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/sxb_icons/iconfont.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.development
    - .env.uat
    - image/1.jpg
    - image/2.jpg
    - image/3.jpg
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
